### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ] Create html document 
- [ ] Add background with css
- [ ] Add car image to html
