### ISSUE TITLE
User can crash their car into obstacles.

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/driving-game#11]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Placed images within the browser will act as obstacles that the car can crash into.

## ✅ Task List

- [ ] Add img elements of obstacles to container
- [ ] Store x, y locations of obstacles in data object
- [ ] Update driveCar function to stop the car if its position is ever equal to one of the obstacle locations
