### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create data model 
- [x] Include property for the direction the car is facing in the data model
- [x] Create css classes for rotating the car
- [x] Listen for keydown events on the document object
- [x] Change the class of the car corresponding to the arrow keydown and the direction the car is currently facing
- [x] Change the car direction in the data model to the new direction
