### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location property to data model
- [x] Set image positioning to absolute
- [x] Set car's inline style for offset
- [x] Make a function that increments image box's left offset
- [x] Add an interval that calls this function every 16ms
- [x] Add event listener to document listening for space bar keydown
- [x] Start car with interval when spacebar is pressed
