### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add boolean to data model indicating if car has started
- [x] On keydown, space, check this boolean
- [x] If it is true clear the interval
